import { DesignSystem } from '../schema/designSystem';

export function exportToJson(system: DesignSystem): string {
  const exportPayload = {
    $schema: 'https://design-tokens.github.io/community-group/format/',
    name: system.overview.name || 'Design System',
    description: system.overview.description,
    version: '1.0.0',
    meta: {
      generatedBy: 'Design.md Visual Explorer',
      sourceFile: system.metadata.fileName,
      parsedAt: system.metadata.parsedAt,
      isAiEnriched: system.metadata.isAiEnriched,
      totalTokens: system.overview.totalTokensCount,
    },
    overview: {
      philosophy: system.overview.philosophy,
      principles: system.overview.principles,
      visualTone: system.overview.visualTone,
    },
    colors: system.colors.reduce((acc, col) => {
      acc[col.id] = {
        $value: col.hex,
        $type: 'color',
        $description: col.role || col.name,
        rgb: col.rgb,
        hsl: col.hsl,
        group: col.paletteGroup,
        aliases: col.aliases,
        confidence: col.confidence,
      };
      return acc;
    }, {} as Record<string, any>),
    typography: system.typography.reduce((acc, typo) => {
      acc[typo.id] = {
        $type: 'typography',
        $value: {
          fontFamily: typo.fontFamily,
          fontSize: typo.fontSize,
          fontWeight: typo.fontWeight,
          lineHeight: typo.lineHeight,
          letterSpacing: typo.letterSpacing,
        },
        $description: typo.role || typo.name,
      };
      return acc;
    }, {} as Record<string, any>),
    spacing: system.spacing.reduce((acc, sp) => {
      acc[sp.id] = {
        $type: 'dimension',
        $value: sp.value,
        px: sp.pxValue,
        rem: sp.remValue,
      };
      return acc;
    }, {} as Record<string, any>),
    radius: system.radii.reduce((acc, rad) => {
      acc[rad.id] = {
        $type: 'dimension',
        $value: rad.value,
        px: rad.pxValue,
      };
      return acc;
    }, {} as Record<string, any>),
    shadows: system.shadows.reduce((acc, shd) => {
      acc[shd.id] = {
        $type: 'shadow',
        $value: shd.value,
        elevation: shd.elevationLevel,
      };
      return acc;
    }, {} as Record<string, any>),
    borders: system.borders.reduce((acc, brd) => {
      acc[brd.id] = {
        $type: 'border',
        $value: `${brd.width} ${brd.style} ${brd.color || ''}`.trim(),
      };
      return acc;
    }, {} as Record<string, any>),
    breakpoints: system.breakpoints.reduce((acc, bp) => {
      acc[bp.id] = {
        $type: 'breakpoint',
        $value: bp.minWidth || `${bp.pxValue}px`,
        px: bp.pxValue,
      };
      return acc;
    }, {} as Record<string, any>),
    components: system.components.map(comp => ({
      name: comp.name,
      description: comp.description,
      anatomy: comp.anatomy,
      variants: comp.variants,
      sizes: comp.sizes,
      states: comp.states,
      tokensUsed: comp.tokensUsed,
      a11yNotes: comp.a11yNotes,
      previewType: comp.previewType,
    })),
    motion: system.motion.map(mot => ({
      name: mot.name,
      duration: mot.duration,
      easing: mot.easing,
      usage: mot.usage,
    })),
    accessibility: system.accessibility.map(a => ({
      title: a.title,
      category: a.category,
      description: a.description,
      wcagLevel: a.wcagLevel,
    })),
  };

  return JSON.stringify(exportPayload, null, 2);
}

export function exportToTailwindV4(system: DesignSystem): string {
  const lines: string[] = [
    '/* Tailwind CSS v4 Theme Extension */',
    '@import "tailwindcss";',
    '',
    '@theme {',
  ];

  if (system.colors.length > 0) {
    lines.push('  /* --- Colors --- */');
    system.colors.forEach(col => {
      const key = col.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      lines.push(`  --color-${key}: ${col.hex};`);
    });
  }

  if (system.spacing.length > 0) {
    lines.push('\n  /* --- Spacing --- */');
    system.spacing.forEach(sp => {
      const key = sp.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      lines.push(`  --spacing-${key}: ${sp.value};`);
    });
  }

  if (system.radii.length > 0) {
    lines.push('\n  /* --- Radii --- */');
    system.radii.forEach(rad => {
      const key = rad.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      lines.push(`  --radius-${key}: ${rad.value};`);
    });
  }

  lines.push('}');
  return lines.join('\n');
}

export function exportToCssVariables(system: DesignSystem): string {
  const lines: string[] = ['/** Generated by Design.md Visual Explorer */', ':root {'];

  if (system.colors.length > 0) {
    lines.push('  /* --- Colors --- */');
    system.colors.forEach(col => {
      const varName = `--color-${col.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
      lines.push(`  ${varName}: ${col.hex}; /* ${col.role || col.paletteGroup} */`);
    });
  }

  if (system.typography.length > 0) {
    lines.push('\n  /* --- Typography --- */');
    system.typography.forEach(t => {
      const varName = `--font-size-${t.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
      lines.push(`  ${varName}: ${t.fontSize};`);
    });
  }

  if (system.spacing.length > 0) {
    lines.push('\n  /* --- Spacing --- */');
    system.spacing.forEach(s => {
      const varName = `--space-${s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
      lines.push(`  ${varName}: ${s.value};`);
    });
  }

  if (system.radii.length > 0) {
    lines.push('\n  /* --- Radii --- */');
    system.radii.forEach(r => {
      const varName = `--radius-${r.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
      lines.push(`  ${varName}: ${r.value};`);
    });
  }

  if (system.shadows.length > 0) {
    lines.push('\n  /* --- Shadows --- */');
    system.shadows.forEach(sh => {
      const varName = `--shadow-${sh.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
      lines.push(`  ${varName}: ${sh.value};`);
    });
  }

  lines.push('}');
  return lines.join('\n');
}

export function exportToTypeScriptTheme(system: DesignSystem): string {
  const colorsObj = system.colors.reduce((acc, c) => {
    const key = c.name.toLowerCase().replace(/[^a-z0-9]+(.)/g, (_, chr) => chr.toUpperCase()).replace(/[^a-zA-Z0-9]/g, '');
    acc[key || 'color'] = c.hex;
    return acc;
  }, {} as Record<string, string>);

  const spacingObj = system.spacing.reduce((acc, s) => {
    const key = s.name.toLowerCase().replace(/[^a-z0-9]+(.)/g, (_, chr) => chr.toUpperCase()).replace(/[^a-zA-Z0-9]/g, '');
    acc[key || 'space'] = s.value;
    return acc;
  }, {} as Record<string, string>);

  const radiusObj = system.radii.reduce((acc, r) => {
    const key = r.name.toLowerCase().replace(/[^a-z0-9]+(.)/g, (_, chr) => chr.toUpperCase()).replace(/[^a-zA-Z0-9]/g, '');
    acc[key || 'radius'] = r.value;
    return acc;
  }, {} as Record<string, string>);

  return `/**
 * TypeScript Design Tokens Definition
 * Auto-generated by Design.md Visual Explorer
 */

export const theme = {
  name: ${JSON.stringify(system.overview.name || 'Design System')},
  colors: ${JSON.stringify(colorsObj, null, 4)},
  spacing: ${JSON.stringify(spacingObj, null, 4)},
  borderRadius: ${JSON.stringify(radiusObj, null, 4)},
} as const;

export type Theme = typeof theme;
export type ThemeColor = keyof typeof theme.colors;
export type ThemeSpacing = keyof typeof theme.spacing;
`;
}

export function exportToScssVariables(system: DesignSystem): string {
  const lines: string[] = ['// SCSS / SASS Variables', '// Generated by Design.md Visual Explorer', ''];

  if (system.colors.length > 0) {
    lines.push('// --- Colors ---');
    system.colors.forEach(col => {
      const varName = `$color-${col.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
      lines.push(`${varName}: ${col.hex};`);
    });
  }

  if (system.spacing.length > 0) {
    lines.push('\n// --- Spacing ---');
    system.spacing.forEach(s => {
      const varName = `$space-${s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
      lines.push(`${varName}: ${s.value};`);
    });
  }

  if (system.radii.length > 0) {
    lines.push('\n// --- Radii ---');
    system.radii.forEach(r => {
      const varName = `$radius-${r.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
      lines.push(`${varName}: ${r.value};`);
    });
  }

  return lines.join('\n');
}

export function exportToTailwindConfig(system: DesignSystem): string {
  const colorEntries = system.colors.map(c => {
    const key = c.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    return `        '${key}': '${c.hex}',`;
  }).join('\n');

  const spacingEntries = system.spacing.map(s => {
    const key = s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    return `        '${key}': '${s.value}',`;
  }).join('\n');

  const radiusEntries = system.radii.map(r => {
    const key = r.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    return `        '${key}': '${r.value}',`;
  }).join('\n');

  return `/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
${colorEntries || '        // No colors parsed'}
      },
      spacing: {
${spacingEntries || '        // No spacing parsed'}
      },
      borderRadius: {
${radiusEntries || '        // No radii parsed'}
      },
    },
  },
};
`;
}

export function exportToAiPromptRules(system: DesignSystem): string {
  const colorList = system.colors.map(c => `- ${c.name}: ${c.hex} (${c.role || c.paletteGroup})`).join('\n');
  const typoList = system.typography.map(t => `- ${t.name}: ${t.fontSize}, weight ${t.fontWeight} (${t.fontFamily})`).join('\n');
  const spaceList = system.spacing.map(s => `- ${s.name}: ${s.value} (${s.pxValue}px)`).join('\n');
  const radiusList = system.radii.map(r => `- ${r.name}: ${r.value}`).join('\n');
  const compList = system.components.map(c => `- ${c.name}: ${c.description || 'UI component'}`).join('\n');
  const a11yList = system.accessibility.map(a => `- ${a.title}: ${a.description}`).join('\n');

  return `# DESIGN SYSTEM GUIDELINES & CONSTRAINTS

You MUST strictly follow this design system specification when generating or modifying any UI components or code.
NEVER invent arbitrary colors, font sizes, or spacing outside these designated tokens.

## Design Identity: ${system.overview.name || 'Core System'}
${system.overview.description || 'Standard design specification.'}
${system.overview.philosophy ? `Philosophy: ${system.overview.philosophy}` : ''}

## Primary Design Tokens

### Colors
${colorList || '- Use standard neutral palette.'}

### Typography
${typoList || '- Default sans-serif scale.'}

### Spacing Grid
${spaceList || '- Standard 4px/8px geometric grid.'}

### Border Radius
${radiusList || '- Standard rounded corners.'}

## Components to Follow
${compList || '- Standard accessible UI components.'}

## Accessibility & Quality Standards
${a11yList || '- Minimum WCAG AA 4.5:1 contrast.\n- Clear focus rings for keyboard navigation.\n- Minimum 44x44px touch target size.'}
`;
}

export function exportToNormalizedMarkdown(system: DesignSystem): string {
  const lines: string[] = [];

  // YAML Frontmatter for AI Agents & Tools
  lines.push('---');
  lines.push(`name: "${system.overview.name || 'Design System'}"`);
  lines.push(`totalTokens: ${system.overview.totalTokensCount}`);
  lines.push('tokens:');
  lines.push('  colors:');
  system.colors.forEach(c => {
    const key = c.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    lines.push(`    ${key}: "${c.hex}"`);
  });
  lines.push('  spacing:');
  system.spacing.forEach(s => {
    const key = s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    lines.push(`    ${key}: "${s.value}"`);
  });
  lines.push('  radius:');
  system.radii.forEach(r => {
    const key = r.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    lines.push(`    ${key}: "${r.value}"`);
  });
  lines.push('---\n');

  lines.push(`# ${system.overview.name || 'Design System'}\n`);
  if (system.overview.description) {
    lines.push(`${system.overview.description}\n`);
  }
  if (system.overview.philosophy) {
    lines.push(`## Philosophy\n\n${system.overview.philosophy}\n`);
  }
  if (system.overview.principles.length > 0) {
    lines.push(`## Core Principles\n`);
    system.overview.principles.forEach(p => lines.push(`* ${p}`));
    lines.push('');
  }

  if (system.colors.length > 0) {
    lines.push(`## Colors\n`);
    lines.push(`| Name | HEX | RGB | Role |`);
    lines.push(`| :--- | :--- | :--- | :--- |`);
    system.colors.forEach(c => {
      lines.push(`| ${c.name} | \`${c.hex}\` | \`${c.rgb}\` | ${c.role || c.paletteGroup} |`);
    });
    lines.push('');
  }

  if (system.typography.length > 0) {
    lines.push(`## Typography\n`);
    lines.push(`| Level | Font Family | Size | Weight | Line Height |`);
    lines.push(`| :--- | :--- | :--- | :--- | :--- |`);
    system.typography.forEach(t => {
      lines.push(`| ${t.name} | ${t.fontFamily} | \`${t.fontSize}\` | ${t.fontWeight} | ${t.lineHeight || '-'} |`);
    });
    lines.push('');
  }

  if (system.spacing.length > 0) {
    lines.push(`## Spacing\n`);
    lines.push(`| Token | Value | Pixels | Role |`);
    lines.push(`| :--- | :--- | :--- | :--- |`);
    system.spacing.forEach(s => {
      lines.push(`| ${s.name} | \`${s.value}\` | ${s.pxValue}px | ${s.role || '-'} |`);
    });
    lines.push('');
  }

  if (system.radii.length > 0) {
    lines.push(`## Border Radius\n`);
    lines.push(`| Token | Value | Pixels |`);
    lines.push(`| :--- | :--- | :--- |`);
    system.radii.forEach(r => {
      lines.push(`| ${r.name} | \`${r.value}\` | ${r.pxValue}px |`);
    });
    lines.push('');
  }

  if (system.shadows.length > 0) {
    lines.push(`## Shadows & Elevation\n`);
    lines.push(`| Level | CSS Value |`);
    lines.push(`| :--- | :--- |`);
    system.shadows.forEach(sh => {
      lines.push(`| ${sh.name} | \`${sh.value}\` |`);
    });
    lines.push('');
  }

  if (system.breakpoints.length > 0) {
    lines.push(`## Breakpoints\n`);
    lines.push(`| Name | Min Width | Pixels |`);
    lines.push(`| :--- | :--- | :--- |`);
    system.breakpoints.forEach(b => {
      lines.push(`| ${b.name} | \`${b.minWidth}\` | ${b.pxValue}px |`);
    });
    lines.push('');
  }

  if (system.components.length > 0) {
    lines.push(`## Components\n`);
    system.components.forEach(c => {
      lines.push(`### ${c.name}\n`);
      if (c.description) lines.push(`${c.description}\n`);
      if (c.variants && c.variants.length > 0) {
        lines.push(`#### Variants\n`);
        c.variants.forEach(v => lines.push(`* **${v.name}**${v.description ? `: ${v.description}` : ''}`));
        lines.push('');
      }
      if (c.states && c.states.length > 0) {
        lines.push(`#### States: ${c.states.join(', ')}\n`);
      }
    });
  }

  if (system.accessibility.length > 0) {
    lines.push(`## Accessibility Guidelines\n`);
    system.accessibility.forEach(a => {
      lines.push(`* **${a.title}** (${a.category}${a.wcagLevel ? `, WCAG ${a.wcagLevel}` : ''}): ${a.description}`);
    });
    lines.push('');
  }

  return lines.join('\n');
}
